#!/bin/bash
set -euo pipefail
trap 'echo FATAL ERROR EXIT CODE $? AT $0:$LINENO' ERR

# jobs is double ncores
make \
    SHELL='bash -euxo pipefail' --debug \
    --jobs $(($(nproc) * 2)) \
    --file ./code/make/Makefile
